global:
  scrape_interval:     30s
  evaluation_interval: 30s
# Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-swarm'
rule_files:
- "alert.rules_nodes"
- "alert.rules_tasks"
- "alert.rules_service-groups"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
#    dns_sd_configs:
#    - names:
#      - 'tasks.prometheus'
#      type: 'A'
#      port: 9090

#- job_name: 'kafka_exporter'
#  dns_sd_configs:
#  - names:
#    - 'tasks.kafka_exporter'
#    type: 'A'
#    port: 9308

#- job_name: 'burrow_exporter'
#  dns_sd_configs:
#  - names:
#    - 'tasks.burrow_exporter'
#    type: 'A'
#    port: 9408


- job_name: 'kafka-exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['kafka-exporter:9308'] 

- job_name: 'zk-exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['zk-exporter:9120'] 

- job_name: 'burrow-exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['burrow-exporter:9408'] 
      
- job_name: 'kafka'
  scrape_interval: 5s
  static_configs:
  - targets: ['broker:7072']

- job_name: 'zookeeper'
  scrape_interval: 5s
  static_configs:
  - targets: ['zookeeper:7070']

- job_name: 'nodeexporter'
  scrape_interval: 5s
  static_configs:
    - targets: ['nodeexporter:9100']

- job_name: 'kafka-generic-consumer'
  scrape_interval: 5s
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: ['kafka-generic-consumer:8080']

