{
 "title": "Host System Metrics - Prometheus Node Exporter 0.16.0",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation, Filesystem usage and Predicted time to filesystems filling. This for the Node Exporter version 0.16.0 or later.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"nodeexporter\"}"
   }
  ]
 },
 "panels": [
  { "title": "Host System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='nodeexporter',instance='$instance'} - node_memory_MemFree_bytes{job='nodeexporter',instance='$instance'} - node_memory_Buffers_bytes{job='nodeexporter',instance='$instance'} - node_memory_Cached_bytes{job='nodeexporter',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='nodeexporter',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='nodeexporter',instance='$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter',instance='$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='nodeexporter',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='nodeexporter',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='nodeexporter',instance='$instance'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Fill Up Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job='nodeexporter',instance='$instance'} - node_filesystem_free_bytes{job='nodeexporter',instance='$instance'}) / deriv(node_filesystem_free_bytes{job='nodeexporter',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''}[3d]) > 0",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "repeat": "node",
     "yaxes": [
      { "format": "bits", "label": "bits in (-) / bits out (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$instance'}[5m])*8 or irate(node_network_receive_bytes{instance=~'$instance'}[5m])*8",
       "legendFormat": "{{device}}_in"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$instance'}[5m])*8 or irate(node_network_transmit_bytes{instance=~'$instance'}[5m])*8",
       "legendFormat": "{{device}}_out"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "graph",
     "description": "Disk Space",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(((node_filesystem_size_bytes{fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{fstype=~\"ext4|vfat\"}) * 100) by (instance)"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$instance\", mode=\"system\"}) or count(node_cpu{instance=~\"$instance\", mode=\"system\"})"
      }
     ]
    }
   ]
  }
 ]
}