{
 "title": "Kafka Metrics",
 "description": "Kafka Metrics",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{instance=~\"$Broker$\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\"$Broker$\"}"
    }
   ]
  },
  {
   "title": "ISR expansion rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrexpands_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "ISR shrink rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinks_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Delayed Fetch operation purgatory size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{instance=~\"$Broker$\"}"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_size{instance=~\"$Broker$\", topic=~\"$Topics$\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kafka_log_size{instance=~\"$Broker$\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\", instance=~\"$Broker$\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",instance=~\"$Broker$\", topic=~\"$Topics$\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",instance=~\"$Broker$\", topic=~\"$Topics$\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",instance=~\"$Broker$\", topic=~\"$Topics$\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number Of Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",instance=~\"$Broker$\", topic=~\"$Topics$\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "$Topics Bytes In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "$Topics Bytes out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\"$Broker$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_total_lag", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Average partition lag by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group)(rate(kafka_burrow_partition_lag[10m]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_underreplicated{instance=~\"$Broker$\", topic=~\"$Topics$\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_server_replicamanager_isrexpands_total{instance=~\"$Broker$\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unclean leader election per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kafka_controller_controllerstats_uncleanleaderelectionspersec{instance=~\"$Broker$\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Fetch requests in Purgatory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_fetch{instance=~\"$Broker.*$\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}