{
 "title": "Zookeeper Metrics",
 "tags": [
  "kafka",
  "zookeeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "zk_instance",
    "label": "ZK Instance",
    "query": "label_values(zk_approximate_data_size, zk_instance)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zk Available Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "up{job=~'zookeeper$'}" }
   ]
  },
  {
   "title": "Zk Followers",
   "type": "singlestat",
   "description": "Zk Followers",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_followers{zk_instance=~\"$zk_instance$\"})"
    }
   ]
  },
  {
   "title": "Zk Server State",
   "type": "singlestat",
   "description": "Zk Server State",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zk_server_state{zk_instance=~\"$zk_instance$\"}"
    }
   ]
  },
  {
   "title": "Nb Live Client Connections",
   "type": "singlestat",
   "description": "Nb Live Client Connections",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_num_alive_connections{zk_instance=~\"$zk_instance$\"})"
    }
   ]
  },
  {
   "title": "Zk Ldr Pending Sync Trans To Disk",
   "type": "singlestat",
   "description": "Zk Ldr Pending Sync Trans To Disk",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_pending_syncs{zk_instance=\"$zk_instance$\"})"
    }
   ]
  },
  {
   "title": "Zk Open File Descriptor Count",
   "type": "singlestat",
   "description": "Zk Open File Descriptor Count",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zk_open_file_descriptor_count{zk_instance=~\"$zk_instance$\"})"
    }
   ]
  },
  {
   "title": "Zk Max File Descriptor Count",
   "type": "singlestat",
   "description": "Zk Max File Descriptor Count",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zk_max_file_descriptor_count{zk_instance=~\"$zk_instance$\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Outstanding Client Requests",
   "type": "graph",
   "description": "Zookeeper Outstanding Client Requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(zk_outstanding_requests{zk_instance=~\"$zk_instance$\"})"
    }
   ]
  },
  {
   "title": "Zookeeper Average Latency",
   "type": "graph",
   "description": "Zookeeper Average Latency",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zk_avg_latency{zk_instance=~\"$zk_instance$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Miscellanous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "zookeeper availability",
     "type": "graph",
     "description": "zookeeper availability",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_ok{job='zk-exporter', zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Election Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_server_state{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}:{{state}}"
      }
     ]
    },
    {
     "title": "Number of connections",
     "type": "graph",
     "description": "zk_num_alive_connections",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_num_alive_connections{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Watches",
     "type": "graph",
     "description": "zk_watch_count number of watches",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_watch_count{job='zk-exporter',zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Client Package sent",
     "type": "graph",
     "description": "zk_packets_sent Number of package sent",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_packets_sent{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Open Files",
     "type": "graph",
     "description": "zk_open_file_descriptor_count Number of open files (must be <85%)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_open_file_descriptor_count{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Nodes",
     "type": "graph",
     "description": "zk_znode_count Number of znodes",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_znode_count{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Temporary Nodes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_ephemerals_count{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data Size",
     "type": "graph",
     "description": "zk_approximate_data_size Data size",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_approximate_data_size{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Queued requests",
     "type": "graph",
     "description": "zk_outstanding_requests Number of queued requests (must be < 10)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_outstanding_requests{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max number of open files",
     "type": "graph",
     "description": "zk_max_file_descriptor_count Max number of allowed open files (ulimit)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_max_file_descriptor_count{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Client Request Packets received",
     "type": "graph",
     "description": "zk_packets_received Number of client request packets received",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_packets_received{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average delay",
     "type": "graph",
     "description": "Average delay",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_avg_latency{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Highest delay",
     "type": "graph",
     "description": "Highest Delay",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_max_latency{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Minimum Delay",
     "type": "graph",
     "description": "Minimum Delay",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zk_min_latency{job=\"zk-exporter\",zk_instance=~\"$zk_instance$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}